[build.environment]
NODE_VERSION = "12.18.0"

# Settings in the [build] context are global and are applied to all contexts
# unless otherwise overridden by more specific contexts.


# The following redirect is intended for use with most SPAs that handle
# routing internally.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200